### ISSUE TITLE
[BUG] - Engine/APU FIRE handle lights during Fire test not working (Freighter only)

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#1008]
### Describe the bug

Currently, during the Engine/APU fire test on the Freighter, all three ENG FIRE handle lights and the APU FIRE handle light fail to illuminate.

### Expected behaviour

![Näyttökuva 2024-04-07 014050](https://github.com/invernyx/md11-bugs/assets/150369113/ff48bebc-dc76-4e7e-a443-506890f35a8b)

### Evidence

![Näyttökuva (1)](https://github.com/invernyx/md11-bugs/assets/150369113/0fe446da-aa0f-4542-a370-89e8b18c0f7c)
![Näyttökuva (2)](https://github.com/invernyx/md11-bugs/assets/150369113/080988c1-2c59-46c3-a943-2c1268b2aba2)

*As per #998, There are some false indications on the EAD

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by joon44** [comment]
The lvars for each 4 lights work correctly.

**Comment by jhattermann** [comment]
This has been fixed in the last merge.

**Comment by moosestaffa83** [comment]
These are still not working in the Freighter at least

**Comment by moosestaffa83** [comment]
> This has been fixed in the last merge.



> This has been fixed in the last merge.

This is still not working in the Freighter GE version as of May 28
