### ISSUE TITLE
[BUG] - Gross weight shown in KG instead of MT (metric tonne) 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1134]
### Describe the bug

Gross weight shown in KG instead of MT (metric tonne) 

### Expected behaviour

To have GW shown in MT 

### Evidence

![Schermopname (522)](https://github.com/invernyx/md11-bugs/assets/150957609/550c6c2a-0987-45d2-9146-b6d0a906076e)
![Schermopname (497)](https://github.com/invernyx/md11-bugs/assets/150957609/e4167297-5b43-4db3-b3bf-4c281785a1b9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+

**Comment by dr71205** [comment]
still showing KG on 0.53 
![image](https://github.com/invernyx/md11-bugs/assets/150094502/24a1cba8-9d8a-4099-b5ca-d8777d7f492b)
