### ISSUE TITLE
[BUG] - Instrument and Pedestal flood lights not working on F (MD-LIGHTS-10)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1231]
### Describe the bug

At night, with instrument/pedestal backlights ON, the flood lights to not adjust when spinning the light reostat

### Steps to reproduce

Turn instrument/pedestal backlights ON
Adjust flood light brightness

### Expected behaviour

Flood light brightness increases as reostat is turned

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I did not see this behavior just now. Is this related to this? https://github.com/invernyx/md11-bugs/issues/400

**Comment by FreakyD777** [comment]
No... #400 has been fixed.  This one shows itself by not controlling the flood lights when using the inner reostat knob.

**Comment by TheFightingRaven** [comment]
#400 is not fixed, overheadlight disfunctional for all variants

**Comment by turbofandude** [comment]
Resolved as of 0.60+
