### ISSUE TITLE
[BUG] - OUTFLOW VALVE DOORS 

### ISSUE THREAD

**Issue by PANAM741** [invernyx/md11-bugs#1429]
### Describe the bug

Outflow valves doors not opening when on ground or depending pressurization cycles.

### Expected behaviour

Please model the opening and closing depending cycles of the outflow valve.

### Evidence

![IMG_5064](https://github.com/invernyx/md11-bugs/assets/71863590/13603927-5f9e-466b-b3a6-c06f511574a9)
![IMG_1201](https://github.com/invernyx/md11-bugs/assets/71863590/15fbff92-9ff1-4e89-8766-f7f2c581a9f6)
![IMG_1203](https://github.com/invernyx/md11-bugs/assets/71863590/c7bd41e4-a074-48ae-b3c5-261743e48898)
![IMG_1200](https://github.com/invernyx/md11-bugs/assets/71863590/0c17e4fe-40ce-48e0-b88b-a46c09d53bda)
![IMG_5036](https://github.com/invernyx/md11-bugs/assets/71863590/08a57834-e4b1-438f-bb3f-af5ac80eda7e)
![IMG_5037](https://github.com/invernyx/md11-bugs/assets/71863590/d0529860-02ac-490c-8a4d-34e333cf5c79)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
Would be an important external model improvement.

**Comment by arwasairl** [comment]
There are no tags for this object neither do I think the door is simulated in the ECS code. @pburnay-invernyx can you confirm?

**Comment by StevenSilvaB767** [comment]
the door doesn't open in the last version 0.62.0-beta(ce) (12 June 2024)

**Comment by pburnay-invernyx** [comment]
@arwasairl the outflow valve is simulated in the ECS.

**Comment by arwasairl** [comment]
Fixed

**Comment by PANAM741** [comment]
Awesome, thanks!

**Comment by StevenSilvaB767** [comment]
Well, I suppose the solution was in parts of the systems, etc. In exterior modeling it is not yet solved since some things are missing and it is obvious because the MD-11 is still in WIP. I think this should come out in the final versions before 1.0. NOTE: in the cabin the arrow or pointer is lost once the GPU is turned on in the plane.
