### ISSUE TITLE
PRESELECT DES page not working

### ISSUE THREAD

**Issue by Geargrip** [invernyx/md11-bugs#1737]
### Describe the bug

The ECON field at lsk2L is not editable

### Steps to reproduce

Enter 300 into scratchpad, press ECON lsk2L, nothing happens

### Expected behaviour

As per the American Airlines MD-11 Operating Manual, during preflight, the PRESELECT DES page is to be updated in the above way to update the ECON descent to POLICY /300.  This means that the descent will be made at ECON Mach then crossover to 300kts.
![Screenshot 2024-08-04 043757](https://github.com/user-attachments/assets/73dcd09d-c3f2-4393-8637-e0f198000716)

### Evidence

Apologies for the 2 screenshots - the steps appear on two pages and wanted to be clear that the bug is documented for the proper page and steps

![Screenshot 2024-08-04 044229](https://github.com/user-attachments/assets/11e8efab-f55d-4193-bb80-6e66e948404c)
![Screenshot 2024-08-04 044246](https://github.com/user-attachments/assets/e07ca378-5854-42e1-adeb-1fdbd501c12e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

GCTS

### Arrival

SBKP

### Cruise level

0

### ZFW

371236

### CG

26

### Fuel

174266

### Cost index

50

### Route

GCTS/07 ODEGI2W ODEGI N873 IPERA UN873 SADBA DCT 04N030W DCT ORARO
DCT 07S040W DCT VUSTO UN741 GEVMI UM654 BIXAN DCT LOLED LOLED1B
SBKP/15

### Location

On ground at GCTS

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.52+

**Comment by KJA1582** [comment]
https://github.com/user-attachments/assets/fde57356-4654-418e-bc0c-edee58670a59

@turbofandude Not fixed

**Comment by KJA1582** [comment]
Nvm, I suck at reading.
