### ISSUE TITLE
[BUG] - APU Air Automatically Turns On After APU Powered On

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#183]
### Describe the bug

APU bleed air turns on after APU powered up via electrical panel

### Steps to reproduce

Cold and Dark
Bat/Ext Power On
Cycle Air system panel to manual and back (it starts in an incorrect state, needs to be cycled for automatic function)
Press APU PWR on APU Panel
Once APU is on speed, APU Air on Air Sys Panel will turn on (verified on Air SD that it is providing air to the system)

### Expected behaviour

APU Air should only turn on when the APU button is selected on the Air Sys panel

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Looks like this was fixed in 0.8

**Comment by GR1MMly** [comment]
> Looks like this was fixed in 0.8

Still happening for me. I should've noted, the Air sys is one you have to recycle to manual and back to function properly. When doing that prior to starting the APU, it will turn APU Air on. If you cycle it after APU is one speed, it'll turn APU air on as well.

**Comment by GenericNerd** [comment]
Verified bug. This is only meant to come on after pilot input. Page 178 of FCOM Vol 3.

**Comment by turbofandude** [comment]
Resolved in 0.19+
