### ISSUE TITLE
[BUG] MD-11 Turns Away When Autoland Is Engaged

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#737]
### Describe the bug

The MD-11 Turns Away When Autoland Is Engaged and does circles.

### Steps to reproduce

Fly the KDEN 34R approach at 9000ft BOENG intersection engage the AUTOLAND. It will show LAND ARMED in the EHSI but instead of staying on the LOC and GS it turned away and did a couple of circles before I took control and landed it. 

### Expected behaviour

I am expecting the LOC and GS will engage and stablize the approach. Also the LOC diamond sat to the right of centered about 5 degrees. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Approach

### Pitch

less than 3 degrees

### Bank

none

### Heading

353

### Altitude

9000

### Departure

RKSI

### Arrival

KDEN

### Cruise level

350

### ZFW

?

### CG

?

### Fuel

172.0K

### Cost index

21

### Route

RKSI/15R N0470F350 EGOB2C EGOBA G597 KAE B467 NOMEX/K0876F350 DCT WDT DCT LUTEL T575 NALAM P175 DITOR T575 OLAMA/K0869F370 T575 BAMOL B484 BE T657 ERNIK/N0477F390 B240 ENM DCT AMOTT J511 TED J133 SIT/N0477F410 DCT DOOZI DCT XT DCT VOLOX DCT MSO DCT RIW DCT TOFUU FLATI3 KDEN/34R

### Location

BOENG intersection on final

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
This has happened to me roughly 12 times.  It's not repeatable even on the same approach at the same airport to the same RW.  I've tried many times to find root cause, but have been unsuccsesfull.

**Comment by KJA1582** [comment]
Were there small circles drawn on the ND route at the waypoint?
Cause I had those drawn circles enroute multiple times and sometimes the AFS tried to make the 360

**Comment by FreakyD777** [comment]
Negative

**Comment by mclovin90** [comment]
Same issue here into KDEN 34L
Was on course and hit the Appr/Land button and aircraft started to turn, When I got closer maybe 12-15nm out and hit the button again it was fine.

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.

**Comment by FreakyD777** [comment]
This is still happening.  In the latest instance, I did some troubleshooting while circling around.  It seems as though if the ILS is manually entered into the NAV/RAD page, then you get this turnaway behaviou and backcourse track.  In this instance, I first manually entered it.  Then after two backcourse turnaways, I cleared it out (had to do it twice) and it then autotuned.  The next approach was w/out incident.
