### ISSUE TITLE
Empty Amber Caution Box on EAD

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#956]
### Describe the bug

On the EAD, there was an empty amber caution box.

### Expected behaviour

The amber box should be populated by the corresponding message, and not blank. However, there were issues with the CG out of limits and a message to select manual on the fuel system, so they may be related.

### Evidence

![Screenshot 2024-03-31 062456](https://github.com/invernyx/md11-bugs/assets/148719444/b195bed2-5a5f-4a95-a250-ce6fc292ee5d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
Didn't see this, I have added a state save here https://github.com/invernyx/md11-bugs/issues/986

**Comment by turbofandude** [comment]
Resolved in 0.310+

**Comment by slowreload** [comment]
Still occurring on on 0.41.0.1
![2024-04-09 11_03_10-Microsoft Flight Simulator - 1 36 2 0](https://github.com/invernyx/md11-bugs/assets/5056361/b1fb90c7-f8b6-42ac-9c3f-9537956cb93a)
